import { images } from "../constants";
const data = {
  slider: [
    {
      img: images.h2,
      tem: "37 , 47' 22.1N  122 23' 49.0 w",
      city: "japan, us-19",
      text: "SALESFORCE",
    },
    {
      img: images.b4,
      tem: "37 , 47' 22.1N  122 23' 49.0 w",
      city: "hoisted , us-19",
      text: "SALESFORCE",
    },
    {
      img: images.s3,
      tem: "37 , 47' 22.1N  122 23' 49.0 w",
      city: " japan , us-19",
      text: "SALESFORCE",
    },
  ],
  works: [
    {
      span: "project / 01 ",
      name: " uber",
      gps: "37°46'26.5N122°2506.7 W",

      clients: " shop",
      location: "san francisco",
      year: "1997",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b1 },
        { img1: images.b7 },
        { img1: images.b6 },
        { img1: images.b2 },
        { img1: images.b3 },
        { img1: images.b4 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 02 ",
      name: "audery irmas pavilion ",
      gps: "37°46'26.5N122°2506.7 W",
      
      clients: " shop",
      location: "san francisco",
      year: "1997",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b1 },
        { img1: images.b4 },
        { img1: images.b7 },
        { img1: images.b2 },
        { img1: images.b3 },
        { img1: images.b4 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 03 ",
      name: "park union bridge",
      gps: "37°46'26.5N122°2506.7 W",
      clients: "shop",
      location: "san francisco",
      year: "1997",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b1 },
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b2 },
        { img1: images.b3 },
        { img1: images.b4 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 04 ",
      name: " 007 elements",
      gps: " gdgvcucjd",
      clients: " shop",
      location: "san francisco",
      year: "1997",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b1 },
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b2 },
        { img1: images.b3 },
        { img1: images.b4 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 06 ",
      name: " amenity bldg 1.0",
      gps: "37°46'26.5N122°2506.7 W",
      clients: " shop",
      location: "san francisco",
      year: "2017",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b3 },
        { img1: images.b1 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 07 ",
      name: " lucid ",
      gps: "37°46'26.5N122°2506.7 W",
      clients: " shop",
      location: "san francisco",
      year: "2017",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b3 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 08 ",
      name: " nvidia ",
      gps: "37°46'26.5N122°2506.7 W",
      clients: " mountain view ",
      location: "san francisco",
      year: "2017",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b3 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 09 ",
      name: " salesforce",
      gps: "37°46'26.5N122°2506.7 W",
      clients: " shop",
      location: "san francisco",
      year: "2017",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b3 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 10 ",
      name: " audrey irmas pavilion",
      gps: "37°46'26.5N122°2506.7 W",
      clients: " shop",
      location: "san francisco",
      year: "2017",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b3 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 11 ",
      name: "49 svn",
      gps: "37°46'26.5N122°2506.7 W",
      clients: " shop",
      location: "san francisco",
      year: "2017",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b3 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 12 ",
      name: "shacke15",
      gps: "37°46'26.5N122°2506.7 W",
      clients: " shop",
      location: "san francisco",
      year: "2017",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b3 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 13 ",
      name: " olympic & paralympic museum",
      gps: "37°46'26.5N122°2506.7 W",
      clients: " shop",
      location: "san francisco",
      year: "2017",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b3 },
        { img1: images.b5 },
      ],
    },
    {
      span: "project / 14 ",
      name: "zendesk",
      gps: "37°46'26.5N122°2506.7 W",
      clients: " shop",
      location: "san francisco",
      year: "2017",
      publication: "ARCHITECTURAL RECORD / METROPOLIS ARCHINECT ",
      img: [
        { img1: images.b7 },
        { img1: images.b4 },
        { img1: images.b3 },
        { img1: images.b5 },
      ],
    },
  ],
};
export default data;
